import React, { Component } from 'react';

class Grid extends Component {

    render() {
        return (
          <div id="grid">
            <div className="gridBox" id="1-0"></div>
            <div className="gridBox" id="1-1"></div>
            <div className="gridBox" id="1-2"></div>
            <div className="gridBox" id="1-3"></div>
            <div className="gridBox" id="1-4"></div>
            <div className="gridBox" id="1-5"></div>
            <div className="gridBox" id="1-6"></div>
            <div className="gridBox" id="1-7"></div>
            <div className="gridBox" id="1-8"></div>
            <div className="gridBox" id="1-9"></div>
            <div className="gridBox" id="1-10"></div>
            <div className="gridBox" id="1-11"></div>
            <div className="gridBox" id="1-12"></div>
            <div className="gridBox" id="1-13"></div>
            <div className="gridBox" id="1-14"></div>
            <div className="gridBox" id="1-15"></div>
            <div className="gridBox" id="1-16"></div>
            <div className="gridBox" id="1-17"></div>
            <div className="gridBox" id="1-18"></div>
            <div className="gridBox" id="1-19"></div>
            <div className="gridBox" id="1-20"></div>
            <div className="gridBox" id="1-21"></div>
            <div className="gridBox" id="1-22"></div>
            <div className="gridBox" id="1-23"></div>
            <div className="gridBox" id="2-0"></div>
            <div className="gridBox" id="2-1"></div>
            <div className="gridBox" id="2-2"></div>
            <div className="gridBox" id="2-3"></div>
            <div className="gridBox" id="2-4"></div>
            <div className="gridBox" id="2-5"></div>
            <div className="gridBox" id="2-6"></div>
            <div className="gridBox" id="2-7"></div>
            <div className="gridBox" id="2-8"></div>
            <div className="gridBox" id="2-9"></div>
            <div className="gridBox" id="2-10"></div>
            <div className="gridBox" id="2-11"></div>
            <div className="gridBox" id="2-12"></div>
            <div className="gridBox" id="2-13"></div>
            <div className="gridBox" id="2-14"></div>
            <div className="gridBox" id="2-15"></div>
            <div className="gridBox" id="2-16"></div>
            <div className="gridBox" id="2-17"></div>
            <div className="gridBox" id="2-18"></div>
            <div className="gridBox" id="2-19"></div>
            <div className="gridBox" id="2-20"></div>
            <div className="gridBox" id="2-21"></div>
            <div className="gridBox" id="2-22"></div>
            <div className="gridBox" id="2-23"></div>
            <div className="gridBox" id="3-0"></div>
            <div className="gridBox" id="3-1"></div>
            <div className="gridBox" id="3-2"></div>
            <div className="gridBox" id="3-3"></div>
            <div className="gridBox" id="3-4"></div>
            <div className="gridBox" id="3-5"></div>
            <div className="gridBox" id="3-6"></div>
            <div className="gridBox" id="3-7"></div>
            <div className="gridBox" id="3-8"></div>
            <div className="gridBox" id="3-9"></div>
            <div className="gridBox" id="3-10"></div>
            <div className="gridBox" id="3-11"></div>
            <div className="gridBox" id="3-12"></div>
            <div className="gridBox" id="3-13"></div>
            <div className="gridBox" id="3-14"></div>
            <div className="gridBox" id="3-15"></div>
            <div className="gridBox" id="3-16"></div>
            <div className="gridBox" id="3-17"></div>
            <div className="gridBox" id="3-18"></div>
            <div className="gridBox" id="3-19"></div>
            <div className="gridBox" id="3-20"></div>
            <div className="gridBox" id="3-21"></div>
            <div className="gridBox" id="3-22"></div>
            <div className="gridBox" id="3-23"></div>
            <div className="gridBox" id="4-0"></div>
            <div className="gridBox" id="4-1"></div>
            <div className="gridBox" id="4-2"></div>
            <div className="gridBox" id="4-3"></div>
            <div className="gridBox" id="4-4"></div>
            <div className="gridBox" id="4-5"></div>
            <div className="gridBox" id="4-6"></div>
            <div className="gridBox" id="4-7"></div>
            <div className="gridBox" id="4-8"></div>
            <div className="gridBox" id="4-9"></div>
            <div className="gridBox" id="4-10"></div>
            <div className="gridBox" id="4-11"></div>
            <div className="gridBox" id="4-12"></div>
            <div className="gridBox" id="4-13"></div>
            <div className="gridBox" id="4-14"></div>
            <div className="gridBox" id="4-15"></div>
            <div className="gridBox" id="4-16"></div>
            <div className="gridBox" id="4-17"></div>
            <div className="gridBox" id="4-18"></div>
            <div className="gridBox" id="4-19"></div>
            <div className="gridBox" id="4-20"></div>
            <div className="gridBox" id="4-21"></div>
            <div className="gridBox" id="4-22"></div>
            <div className="gridBox" id="4-23"></div>
            <div className="gridBox" id="5-0"></div>
            <div className="gridBox" id="5-1"></div>
            <div className="gridBox" id="5-2"></div>
            <div className="gridBox" id="5-3"></div>
            <div className="gridBox" id="5-4"></div>
            <div className="gridBox" id="5-5"></div>
            <div className="gridBox" id="5-6"></div>
            <div className="gridBox" id="5-7"></div>
            <div className="gridBox" id="5-8"></div>
            <div className="gridBox" id="5-9"></div>
            <div className="gridBox" id="5-10"></div>
            <div className="gridBox" id="5-11"></div>
            <div className="gridBox" id="5-12"></div>
            <div className="gridBox" id="5-13"></div>
            <div className="gridBox" id="5-14"></div>
            <div className="gridBox" id="5-15"></div>
            <div className="gridBox" id="5-16"></div>
            <div className="gridBox" id="5-17"></div>
            <div className="gridBox" id="5-18"></div>
            <div className="gridBox" id="5-19"></div>
            <div className="gridBox" id="5-20"></div>
            <div className="gridBox" id="5-21"></div>
            <div className="gridBox" id="5-22"></div>
            <div className="gridBox" id="5-23"></div>
            <div className="gridBox" id="6-0"></div>
            <div className="gridBox" id="6-1"></div>
            <div className="gridBox" id="6-2"></div>
            <div className="gridBox" id="6-3"></div>
            <div className="gridBox" id="6-4"></div>
            <div className="gridBox" id="6-5"></div>
            <div className="gridBox" id="6-6"></div>
            <div className="gridBox" id="6-7"></div>
            <div className="gridBox" id="6-8"></div>
            <div className="gridBox" id="6-9"></div>
            <div className="gridBox" id="6-10"></div>
            <div className="gridBox" id="6-11"></div>
            <div className="gridBox" id="6-12"></div>
            <div className="gridBox" id="6-13"></div>
            <div className="gridBox" id="6-14"></div>
            <div className="gridBox" id="6-15"></div>
            <div className="gridBox" id="6-16"></div>
            <div className="gridBox" id="6-17"></div>
            <div className="gridBox" id="6-18"></div>
            <div className="gridBox" id="6-19"></div>
            <div className="gridBox" id="6-20"></div>
            <div className="gridBox" id="6-21"></div>
            <div className="gridBox" id="6-22"></div>
            <div className="gridBox" id="6-23"></div>
            <div className="gridBox" id="0-0"></div>
            <div className="gridBox" id="0-1"></div>
            <div className="gridBox" id="0-2"></div>
            <div className="gridBox" id="0-3"></div>
            <div className="gridBox" id="0-4"></div>
            <div className="gridBox" id="0-5"></div>
            <div className="gridBox" id="0-6"></div>
            <div className="gridBox" id="0-7"></div>
            <div className="gridBox" id="0-8"></div>
            <div className="gridBox" id="0-9"></div>
            <div className="gridBox" id="0-10"></div>
            <div className="gridBox" id="0-11"></div>
            <div className="gridBox" id="0-12"></div>
            <div className="gridBox" id="0-13"></div>
            <div className="gridBox" id="0-14"></div>
            <div className="gridBox" id="0-15"></div>
            <div className="gridBox" id="0-16"></div>
            <div className="gridBox" id="0-17"></div>
            <div className="gridBox" id="0-18"></div>
            <div className="gridBox" id="0-19"></div>
            <div className="gridBox" id="0-20"></div>
            <div className="gridBox" id="0-21"></div>
            <div className="gridBox" id="0-22"></div>
            <div className="gridBox" id="0-23"></div>
          </div>
        );
    }
}

export default Grid;
